dtb-$(CONFIG_SOC_GS201) += \
        gs201-a0.dtb \

dtbo-y += \
        gs201-tangorpro-evt2.dtbo \
        gs201-tangorpro-evt2-wingboard.dtbo \
        gs201-tangorpro-dvt1.dtbo \
        gs201-tangorpro-pvt1.dtbo \
        gs201-tangorpro-mp.dtbo

gs201-tangorpro-evt2.dtbo-base := google-base/gs201-a0.dtb
gs201-tangorpro-evt2-wingboard.dtbo-base := google-base/gs201-a0.dtb
gs201-tangorpro-dvt1.dtbo-base := google-base/gs201-a0.dtb
gs201-tangorpro-pvt1.dtbo-base := google-base/gs201-a0.dtb
gs201-tangorpro-mp.dtbo-base := google-base/gs201-a0.dtb

MKDTIMG_FLAGS += --page_size=4096  --id=/:board_id --rev=/:board_rev
